FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

# JAR 파일 복사 (GitHub Actions에서 빌드된 JAR 파일)
COPY app/build/libs/*.jar app.jar

# 환경 변수 설정
ENV SPRING_PROFILES_ACTIVE=prod
ENV SERVER_PORT=8080

# 컨테이너 실행 시 비-루트 사용자로 실행
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

# 포트 노출
EXPOSE 8080
EXPOSE 80
EXPOSE 88
EXPOSE 433

# 애플리케이션 실행
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
