/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Spring Boot
    id("org.springframework.boot") version "3.1.3"
    id("io.spring.dependency-management") version "1.1.0"

    // Kotlin
    alias(libs.plugins.kotlin.jvm)
    kotlin("plugin.spring") version "1.9.21"
    kotlin("plugin.jpa")    version "1.9.21"
    kotlin("kapt")           version "1.9.21"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Swagger/OpenAPI
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0")
    kapt         ("org.springdoc:springdoc-openapi-kotlin:2.1.0")

    // 기타
    implementation(libs.guava)

    // 테스트
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    testImplementation(libs.junit.jupiter.engine)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
